//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VisualStudio.BizTalkProject.Generators generó automáticamente este código fuente, versión 4.0.30319.34014.
// 
namespace AES.UniversalBank.Messaging.BrokerProcess.AccountService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IAccountService", Namespace="http://www.universalbank.com/aes/services")]
    [Microsoft.XLANGs.BaseTypes.WebServiceUrlAttribute("http://localhost:28958/AccountService.svc")]
    public partial class AccountService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public AccountService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["AES.UniversalBank.Messaging.BrokerProcess.AccountService.AccountService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost:28958/AccountService.svc";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbank.com/aes/services/IAccountService/GetCustomerAccounts", RequestNamespace="http://www.universalbank.com/aes/services", ResponseNamespace="http://www.universalbank.com/aes/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
        public Account[] GetCustomerAccounts([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerId) {
            object[] results = this.Invoke("GetCustomerAccounts", new object[] {
                        customerId});
            return ((Account[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomerAccounts(string customerId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomerAccounts", new object[] {
                        customerId}, callback, asyncState);
        }
        
        /// <remarks/>
        public Account[] EndGetCustomerAccounts(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Account[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbank.com/aes/services/IAccountService/GetAccountTransactions", RequestNamespace="http://www.universalbank.com/aes/services", ResponseNamespace="http://www.universalbank.com/aes/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
        public AccountTransaction[] GetAccountTransactions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("GetAccountTransactions", new object[] {
                        id});
            return ((AccountTransaction[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAccountTransactions(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAccountTransactions", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public AccountTransaction[] EndGetAccountTransactions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AccountTransaction[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbank.com/aes/services/IAccountService/AddAccountTransaction", RequestNamespace="http://www.universalbank.com/aes/services", ResponseNamespace="http://www.universalbank.com/aes/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddAccountTransaction([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string accountId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] AccountTransaction transaction) {
            this.Invoke("AddAccountTransaction", new object[] {
                        accountId,
                        transaction});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddAccountTransaction(string accountId, AccountTransaction transaction, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddAccountTransaction", new object[] {
                        accountId,
                        transaction}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAddAccountTransaction(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
    public partial class Account {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> BalanceDate;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool BalanceDateSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> BalanceValue;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool BalanceValueSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Type;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
    public partial class AccountTransaction {
    }
}
