//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.universalbank.com/aes/broker", ConfigurationName="BizTalkServiceReference.AccountInfoBroker")]
    public interface AccountInfoBroker {
        
        // CODEGEN: Generating message contract since the operation GetCustomerProfile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileResponse GetCustomerProfile(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileResponse> GetCustomerProfileAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCustomerAccounts is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerAccounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsResponse GetCustomerAccounts(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsResponse> GetCustomerAccountsAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCustomerPayments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerPayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsResponse GetCustomerPayments(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerPayments", ReplyAction="*")]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsResponse> GetCustomerPaymentsAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCustomerLoans is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerLoans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansResponse GetCustomerLoans(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetCustomerLoans", ReplyAction="*")]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansResponse> GetCustomerLoansAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.universalbank.com/aes/broker/schemas")]
    public partial class AccountInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIdField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
                this.RaisePropertyChanged("CustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="token", Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.universalbank.com/aes/broker/schemas")]
    public partial class Customer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string emailField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest;
        
        public GetCustomerProfileRequest() {
        }
        
        public GetCustomerProfileRequest(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            this.AccountInfoRequest = AccountInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Customer Customer;
        
        public GetCustomerProfileResponse() {
        }
        
        public GetCustomerProfileResponse(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Customer Customer) {
            this.Customer = Customer;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.universalbank.com/aes/broker/schemas")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string typeField;
        
        private System.Nullable<decimal> balanceValueField;
        
        private System.Nullable<System.DateTime> balanceDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> BalanceValue {
            get {
                return this.balanceValueField;
            }
            set {
                this.balanceValueField = value;
                this.RaisePropertyChanged("BalanceValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> BalanceDate {
            get {
                return this.balanceDateField;
            }
            set {
                this.balanceDateField = value;
                this.RaisePropertyChanged("BalanceDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest;
        
        public GetCustomerAccountsRequest() {
        }
        
        public GetCustomerAccountsRequest(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            this.AccountInfoRequest = AccountInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Account", IsNullable=false)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Account[] AccountList;
        
        public GetCustomerAccountsResponse() {
        }
        
        public GetCustomerAccountsResponse(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Account[] AccountList) {
            this.AccountList = AccountList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.universalbank.com/aes/broker/schemas")]
    public partial class Payment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerPaymentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest;
        
        public GetCustomerPaymentsRequest() {
        }
        
        public GetCustomerPaymentsRequest(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            this.AccountInfoRequest = AccountInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerPaymentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Payment", IsNullable=false)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Payment[] PaymentList;
        
        public GetCustomerPaymentsResponse() {
        }
        
        public GetCustomerPaymentsResponse(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Payment[] PaymentList) {
            this.PaymentList = PaymentList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.universalbank.com/aes/broker/schemas")]
    public partial class Loan : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private System.DateTime startDateField;
        
        private int payoffField;
        
        private int paymentCountField;
        
        private decimal paymentValueField;
        
        private System.Nullable<decimal> nextPaymentValueField;
        
        private System.Nullable<decimal> totalPaymentValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("StartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Payoff {
            get {
                return this.payoffField;
            }
            set {
                this.payoffField = value;
                this.RaisePropertyChanged("Payoff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PaymentCount {
            get {
                return this.paymentCountField;
            }
            set {
                this.paymentCountField = value;
                this.RaisePropertyChanged("PaymentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal PaymentValue {
            get {
                return this.paymentValueField;
            }
            set {
                this.paymentValueField = value;
                this.RaisePropertyChanged("PaymentValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> NextPaymentValue {
            get {
                return this.nextPaymentValueField;
            }
            set {
                this.nextPaymentValueField = value;
                this.RaisePropertyChanged("NextPaymentValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> TotalPaymentValue {
            get {
                return this.totalPaymentValueField;
            }
            set {
                this.totalPaymentValueField = value;
                this.RaisePropertyChanged("TotalPaymentValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerLoansRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest;
        
        public GetCustomerLoansRequest() {
        }
        
        public GetCustomerLoansRequest(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            this.AccountInfoRequest = AccountInfoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerLoansResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.universalbank.com/aes/broker/schemas", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Loan", IsNullable=false)]
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Loan[] LoanList;
        
        public GetCustomerLoansResponse() {
        }
        
        public GetCustomerLoansResponse(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Loan[] LoanList) {
            this.LoanList = LoanList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountInfoBrokerChannel : AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountInfoBrokerClient : System.ServiceModel.ClientBase<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker>, AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker {
        
        public AccountInfoBrokerClient() {
        }
        
        public AccountInfoBrokerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountInfoBrokerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountInfoBrokerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountInfoBrokerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileResponse AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerProfile(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest request) {
            return base.Channel.GetCustomerProfile(request);
        }
        
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Customer GetCustomerProfile(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileResponse retVal = ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerProfile(inValue);
            return retVal.Customer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileResponse> AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerProfileAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest request) {
            return base.Channel.GetCustomerProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileResponse> GetCustomerProfileAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerProfileRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            return ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsResponse AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerAccounts(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest request) {
            return base.Channel.GetCustomerAccounts(request);
        }
        
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Account[] GetCustomerAccounts(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsResponse retVal = ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerAccounts(inValue);
            return retVal.AccountList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsResponse> AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerAccountsAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest request) {
            return base.Channel.GetCustomerAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsResponse> GetCustomerAccountsAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerAccountsRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            return ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerAccountsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsResponse AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerPayments(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest request) {
            return base.Channel.GetCustomerPayments(request);
        }
        
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Payment[] GetCustomerPayments(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsResponse retVal = ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerPayments(inValue);
            return retVal.PaymentList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsResponse> AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerPaymentsAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest request) {
            return base.Channel.GetCustomerPaymentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsResponse> GetCustomerPaymentsAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerPaymentsRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            return ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerPaymentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansResponse AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerLoans(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest request) {
            return base.Channel.GetCustomerLoans(request);
        }
        
        public AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.Loan[] GetCustomerLoans(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansResponse retVal = ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerLoans(inValue);
            return retVal.LoanList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansResponse> AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker.GetCustomerLoansAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest request) {
            return base.Channel.GetCustomerLoansAsync(request);
        }
        
        public System.Threading.Tasks.Task<AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansResponse> GetCustomerLoansAsync(AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoRequest AccountInfoRequest) {
            AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest inValue = new AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.GetCustomerLoansRequest();
            inValue.AccountInfoRequest = AccountInfoRequest;
            return ((AES.UniversalBank.Messaging.Broker.Impl.BizTalkServiceReference.AccountInfoBroker)(this)).GetCustomerLoansAsync(inValue);
        }
    }
}
