//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VisualStudio.BizTalkProject.Generators generó automáticamente este código fuente, versión 4.0.30319.34014.
// 
namespace AES.UniversalBank.Messaging.BrokerProcess.PaymentService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPaymentsService", Namespace="http://www.universalbank.com/aes/services")]
    [Microsoft.XLANGs.BaseTypes.WebServiceUrlAttribute("http://localhost:45323/PaymentsService.svc")]
    public partial class PaymentsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public PaymentsService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["AES.UniversalBank.Messaging.BrokerProcess.PaymentService.PaymentsService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost:45323/PaymentsService.svc";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbank.com/aes/services/IPaymentsService/GetCustomerPayments", RequestNamespace="http://www.universalbank.com/aes/services", ResponseNamespace="http://www.universalbank.com/aes/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
        public Payment[] GetCustomerPayments([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string customerId) {
            object[] results = this.Invoke("GetCustomerPayments", new object[] {
                        customerId});
            return ((Payment[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCustomerPayments(string customerId, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCustomerPayments", new object[] {
                        customerId}, callback, asyncState);
        }
        
        /// <remarks/>
        public Payment[] EndGetCustomerPayments(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Payment[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbank.com/aes/services/IPaymentsService/GetPayment", RequestNamespace="http://www.universalbank.com/aes/services", ResponseNamespace="http://www.universalbank.com/aes/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Payment GetPayment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("GetPayment", new object[] {
                        id});
            return ((Payment)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPayment(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPayment", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public Payment EndGetPayment(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Payment)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbank.com/aes/services/IPaymentsService/SavePayment", RequestNamespace="http://www.universalbank.com/aes/services", ResponseNamespace="http://www.universalbank.com/aes/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SavePayment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Payment payment) {
            this.Invoke("SavePayment", new object[] {
                        payment});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSavePayment(Payment payment, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SavePayment", new object[] {
                        payment}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSavePayment(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbank.com/aes/services/IPaymentsService/GetPaymentRecords", RequestNamespace="http://www.universalbank.com/aes/services", ResponseNamespace="http://www.universalbank.com/aes/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
        public PaymentRecord[] GetPaymentRecords([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id) {
            object[] results = this.Invoke("GetPaymentRecords", new object[] {
                        id});
            return ((PaymentRecord[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPaymentRecords(string id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPaymentRecords", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public PaymentRecord[] EndGetPaymentRecords(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PaymentRecord[])(results[0]));
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
    public partial class Payment {
        
        /// <comentarios/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public int DayOfMonth;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool DayOfMonthSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Description;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Id;
        
        /// <comentarios/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool Recurring;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool RecurringSpecified;
        
        /// <comentarios/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public System.DateTime StartDate;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool StartDateSpecified;
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBank.Common.Entities")]
    public partial class PaymentRecord {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string PaymentId;
        
        /// <comentarios/>
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public System.DateTime ProcessDate;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public bool ProcessDateSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Status;
    }
}
