//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VisualStudio.BizTalkProject.Generators generó automáticamente este código fuente, versión 4.0.30319.34014.
// 
namespace AES.UniversalBank.Messaging.BrokerProcess.CustomerService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ICustomerService", Namespace="http://www.universalbankcrm.com")]
    [Microsoft.XLANGs.BaseTypes.WebServiceUrlAttribute("http://localhost:30111/CustomerService.svc")]
    public partial class CustomerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CustomerService() {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["AES.UniversalBank.Messaging.BrokerProcess.CustomerService.CustomerService"];
            if ((urlSetting != null)) {
                this.Url = string.Concat(urlSetting, "");
            }
            else {
                this.Url = "http://localhost:30111/CustomerService.svc";
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.universalbankcrm.com/ICustomerService/FindCustomerByEmail", RequestNamespace="http://www.universalbankcrm.com", ResponseNamespace="http://www.universalbankcrm.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Customer FindCustomerByEmail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email) {
            object[] results = this.Invoke("FindCustomerByEmail", new object[] {
                        email});
            return ((Customer)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginFindCustomerByEmail(string email, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("FindCustomerByEmail", new object[] {
                        email}, callback, asyncState);
        }
        
        /// <remarks/>
        public Customer EndFindCustomerByEmail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Customer)(results[0]));
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/AES.UniversalBankCRM")]
    public partial class Customer {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Address;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Email;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string FirstName;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string Id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [Microsoft.XLANGs.BaseTypes.DistinguishedFieldAttribute()]
        public string LastName;
    }
}
